flags: {}
packages:
- '.'
- location:
    git: git@github.com:konn/ghc-typelits-presburger.git
    commit: 9753a88eeed90f5ae70b9e42bb33bb15ee564130
  extra-dep: true
- location:
    git: git@github.com:konn/equational-reasoning-in-haskell.git
    commit: b0c47234b4f02b9dc1ccc15c9b13054f2625b7e3
  extra-dep: true

extra-deps: 
- monomorphic-0.0.3.3
- singletons-2.1
- th-desugar-1.6
- ghc-typelits-natnormalise-0.4.6
# - equational-reasoning-0.3.0.0
resolver: lts-6.8
